# Generated by Django 5.0.4 on 2024-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_social_github_profile_social_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
    ]
