# Generated by Django 5.0.4 on 2024-05-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_kelvin_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelvin',
            old_name='owner',
            new_name='own',
        ),
    ]
