# Generated by Django 5.0.4 on 2024-05-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_owner_kelvin_own'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelvin',
            name='own',
        ),
    ]
